name: Build drtk gui frontend

# Trigger automatically when changes are made in the drtk-cli
on:
  push:
    paths:
      - 'drtk-gui/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: cd .\drtk-gui\ && dotnet restore

      - name: Build and publish project
        run: cd .\drtk-gui\ && dotnet publish -c Release -r win-x64 --self-contained

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: drtk-gui
          path: drtk-gui/bin/net8.0/win-x64/publish/
